name: '🤖'
on:
  workflow_dispatch:
  schedule:
    - cron: '20 4 * * *'
permissions:
  contents: write
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "EPOCH=$(date +%s)" >> $GITHUB_ENV
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.EPOCH }}',
              sha: context.sha
            })
